myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from pages import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('logout/', views.user_logout, name='user_logout'),
    path('home/', views.homepageview, name='home'),
     #NEW
]

myblog/pages/urls.py
from django.urls import path
from .views import homepageview, aboutpageview, base, formpageview, register, user_login, user_logout


app_name = 'pages'  

urlpatterns = [

path('', homepageview, name='home'),
path ('about/',aboutpageview, name='about'),
path('base/', base, name='base'),
path('formpage/', formpageview, name='formpage'),
path('registration/', register, name = 'registration'),
path('login/',user_login, name='user_login'), 
#path('user_logout/' ,user_logout, name='user_logout'),  
]

myblog/pages/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
 
class Post(models.Model):
    text = models.TextField(max_length=200, unique=True) 

    def __str__(self):
        return self.text 

class Author(models.Model):
    post = models.ForeignKey(Post, on_delete= models.CASCADE)
    name = models.CharField(max_length=50, unique=True)
 
    def __str__(self): 
        return self.name 
 
class Date(models.Model):
    name = models.ForeignKey(Author, on_delete= models.CASCADE)
    date = models.DateField() 
  
    def __str__(self):    
        return str(self.date)

    
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # adding your personal attributes
    portfolio_site = models.CharField(blank=True, max_length=50)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank=True)

    def __str__(self):
        return self.user.username

myblog/pages/forms.py
from django import forms
from django.core import validators
from .models import Author, UserProfileInfo
from django.contrib.auth.models import User




class FormName(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    verify_email = forms.EmailField( label="input your email again ")
    text = forms.CharField(widget=forms.Textarea) 
 


    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if email != vmail:
            raise forms.ValidationError('emails should match')
        else:
            pass

class NewUserForm(forms.ModelForm):
    class Meta():
        model = Author
        fields = '__all__'

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

myblog/pages/views.py
from django.shortcuts import render
from .models import Post, Author, Date
from . import forms 
from pages.forms import UserProfileInfoForm, UserForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse



def homepageview(request):  
    homepage_list = Date.objects.order_by('date')
    list_dict = {'list_records': homepage_list} 
    return render(request, 'pages/home.html', context= list_dict)

def aboutpageview(request):  
    my_dict = {'des':'your welcome'}
    return render(request, 'pages/about.html', context=my_dict)
  
def base(request): 
    return render(request, 'pages/base.html') 
# Create your views here.

def formpageview(request):
    form = forms.NewUserForm

    if request.method == 'POST':
        form = forms.NewUserForm(request.POST)
        if form.is_valid():
            form.save(commit=True) 
        else:
            print("ERROR FORM COULDNT SAVE")

    return render(request, 'pages/formpage.html', {'form':form})

def register(request):
    registered = False

    if request.method == 'POST':
        user_form  = UserForm(data= request.POST)
        profile_form = UserProfileInfoForm(data= request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
 
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'pages/registration.html', {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})

     


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password') 

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('home'))


            else:
               return HttpResponse('wrong username or password')
        else:
            print('person wan hack in oooh')
            print('him wan use uesrname:{} and password:{}'.format(username, password))
            return HttpResponse("wrong details")
    else:
        return render(request, 'pages/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

@login_required
def special_view(request):
    return HttpResponse("successful good your logged in")

myblog/templates/pages/about.html
<!DOCTYPE html>
{% extends 'pages/base.html' %}
{% block content %}
<h4>About page</h4>
<h1>{{ des }}</h1>
{% endblock %}

myblog/templates/pages/base.html
<header>
    <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <a href="{% url 'pages:home'%}"> home page</a>| <a href="{% url 'pages:about'%}">About page</a>
    {% if user.is_authenticated %}
    <li><a href="{% url 'user_logout' %}">Logout</a></li>
    {% else %}
    <li><a href="{% url 'pages:user_login' %}">Login</a></li>
    {% endif%}

</header>
{% block content %}
{% endblock %}

myblog/templates/pages/formpage.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <title>Forms</title>
    </head>
    <body>
        <h1>Form Page</h1>
        <div class="container">
            <form method="POST">
            {{form.as_p}}
            {% csrf_token %}
            <input type="submit" value="submit" class="btn btn-primary">
          </form>
        </div>
    </body>
</html>

myblog/templates/pages/home.html
<!DOCTYPE html>
{% extends 'pages/base.html' %}
{% block content %}
<h1>hey</h1>
<h2>this from the dataBase</h2>
<div>
{% if list_records %}
{% for lis in list_records %}
<h2>{{ lis.date }}</h2>
<h2>{{ lis.name }}</h2>
<h2>{{ lis.post }}</h2>
{% endfor %}
{% else %}
    <p>couldnt load </p>
{% endif %}
</div>
{% endblock %}

myblog/templates/pages/login.html
{% extends 'pages/base.html' %}
{% block content %}

<div class="jumbotron">
<h1>pls login here with the detials required</h1>
<form action="{% url 'pages:user_login' %}" method="POST">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="enter username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" value="Login">
</form>
</div>
{% endblock %}

myblog/templates/pages/registration.html
<!DOCTYPE html>
{% extends 'pages/base.html' %}
{% block content %}
{% if registered %}
<h2>thanks for registrating</h2>
{% else %}
<h2>pls register here</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
{{user_form.as_p}}
{{profile_form.as_p}}
<input type="submit" value="submit" class="btn btn-primary">
</form>
{% endif %}
{% endblock %}